version: '3.8'
services:
  db:
    image: postgres:14.2-alpine
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
  api: 
    build:
      context: .
    ports:
      - 8080:8080
    depends_on:
      - db
volumes:
  postgres: